label ch4_main:
    stop music fadeout 2.0
    scene bg residential_day
    with dissolve_scene_full

    play music t6

    "Pazar günü geldi çattı."
    if ch4_scene == "natsuki":
        "Natsuki’nin ziyareti beni inanılmaz derecede geriyordu."
        "Kendime gerilmeye gerek olmadığını söylesem de pek bir yardımı dokunmuyor."
        "Acaba ikimiz başbaşayken farklı davranır mı?"
        "Bu sırada, Natsuki bana bol bol mesaj yolluyordu."
        "Birbirimize numaralarımızı verdikten sonra emin olmak için ikimiz de birbirimize mesaj atmıştık. Çok geçmeden mesajlarımız bir sohbete dönüştü."
        "Natsuki telefonda neredeyse bambaşka biri. Bol bol emoji kullanıp şirin bir dilde yazıyor."
        "Bir de genel olarak sızlanmayı çok seviyor ama böyle olacağını biliyordum."
        "Ama Natsuki bir kenara..."
    else:
        "Yuri’nin ziyareti beni inanılmaz derecede geriyordu."
        "Kendime gerilmeye gerek olmadığını söylesem de pek bir yardımı dokunmuyor."
        "Yuri genel olarak içine kapanık ama bir o kadar da samimi biri."
        "Başbaşayken biraz açılacağına şüphe yok."
        "Bu sırada, aralıklarla mesajlaşıyorduk."
        "İlk başta son derece endişeliydi ama çok geçmeden onun hakkında daha fazla şey öğrenmiştim."
        "Ama Yuri bir kenara..."
    "Geçen gün kulüp odasından erken çıktığı günden beri Sayori’den haber almadım."
    "Birbirimizle durmadan mesajlaştığımız falan yok ama..."
    "Onun hakkında endişeliydim."
    "Sayori’nin ve Monika’nın dediklerini düşünüyorum da..."
    "Bana ihtiyaç duyabileceği bir zamanda Sayori’nin duygularını bir kenara koymak doğru bir şey mi?"

    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "[ch4_name] gelmeden önce Sayori’yi ziyaret etmeye karar veriyorum."
    "Ona gelebilir miyim diye sormaktansa eskiden yaptığımız gibi ona “Sana geliyorum” yazıyorum."
    "Sayori’nin evine vardığımda içeri girmeden önce kapıyı çalıyorum."
    "Eskiden o kadar çok birbirimizle oynardık ki aynı ailedenmişiz gibi birbirimizin evine girmeyi alışkanlık hâline getirmiştik."
    scene black with wipeleft
    "Ev sessiz."
    "Sayori zemin katın hiçbir yerinde değildi, o yüzden odasında olduğunu düşünüyorum."
    "Aşağı koşup beni karşılamaması başlı başına garip zaten."
    "Yatak odasına çıkıp sonunda onu orada buluyorum."
    scene bg sayori_bedroom with wipeleft
    mc "Sayori?"
    play music t10
    show sayori 1ba zorder 2 at t11
    s "Merhaba [player]~"
    show sayori 1by
    "Odasına girip oturuyorum."
    "Sayori gülümsemeye çalışıyor ama bir şeylerin farklı olduğu bariz ortada."
    "Aramızda bir dakikalık bir sessizlik oluyor."
    s "Uzun süredir evime böyle gelmiyordun, değil mi?"
    mc "A... Sanırım haklısın."
    mc "Uzun zaman oldu."
    mc "Çok fazla şey değişmemiş, değil mi?"
    "Sayori’nin odası her zamanki gibi dağınık."
    "Yıllardır değiştirmediği pelüş hayvanları ve duvar dekorasyonlarını da tanıyorum."
    s 2bl "Ehehe~"
    s "Daha sık uğrasaydın bu kadar dağınık olmazdı."
    mc "Çünkü odanı hep ben temizliyordum..."
    s 1bb "Nereden esti de geldin bugün?"
    s "[ch4_name]’yle buluşmayacak mıydın?"
    mc "Evet de..."
    mc "... Bir dakika, sen nereden biliyorsun?"
    "Sayori, biz bunu kararlaştırmadan önce kulüp odasını terk etmişti zaten."
    s 1ba "Monika söyledi."
    s "Beni festival hazırlıkları konusunda bilgilendirmesi normal, değil mi?"
    mc "A, doğru..."
    mc "Peki ya sen?"
    mc "Bugün Monika’ya yardım etmen gerekmiyor muydu?"
    s 4bb "Elbette!"
    s "Ama ona internetten yardım ediyorum."
    s "Buluşmaya falan karar vermedik."
    mc "Ha, yani sadece [ch4_name] ile ben buluşuyoruz..."
    s 1ba "Aynen~"
    "Aramızda bir süre daha sessizlik oluyor."
    show sayori 1bk
    "Sayori gelişigüzel bir yöne doğru bakıyor."
    "Şu an hiç kendisi gibi davranmıyor."
    "Sadede geliyorum."
    mc "Sadece... Nasıl olduğunu görmek istedim."
    mc "Cuma günü öyle çekip gittin."
    mc "Bir sorunun olduğunda benden saklayamazsın!"
    mc "Seni çok iyi tanıyorum."
    mc "O yüzden..."
    "Sayori gülümseyip başını sallıyor."
    s 1bd "Böyle olmaz, [player]."
    mc "Ha?"
    s "Neden her şey eskisi gibi olamıyor ki?"
    s 1by "Hepsi benim suçum."
    s "Bu kadar zayıf düşüp hislerimi belli etmeseydim..."
    s 1bk "O aptal hatayı yapmasaydım..."
    s "Benim hakkımda endişelenmezdin bile."
    s "Buraya gelmezdin."
    s 1bd "Şu an beni düşünüyor olmazdın."
    s "Ama bu... benim cezam, öyle değil mi?"
    s "Bu kadar bencil olduğum için cezalandırılıyorum."
    s "Sanırım bu yüzden evren senin bugün evime uğramana karar verdi."
    s "Evren bana işkence etmek istiyor."
    s 4bq "Ehehe~"
    mc "Sayori!"
    show sayori 4bb
    "Sayori’yi omuzlarından tutuyorum."
    mc "Neler diyorsun sen?!"
    mc "Ağzından çıkanı kulağın duyuyor mu?"
    mc "Sana bir şey olduğunu biliyorum."
    mc "Böyle davranıyor olmanın başka açıklaması yok."
    mc "Anlat bana artık!.."
    mc "Sorunun ne olduğunu öğrenemezsem kafayı yerim!"
    s 4bl "A..."
    s "Ahaha..."
    "Sayori bana boş bir gülümsemeyle karşılık veriyor."
    s 4by "Beni gerçekten zor duruma sokuyorsun, [player]."
    s "Ama..."
    s 1ba "Yanılıyorsun."
    s "Bana hiçbir şey olmadı."
    s "Ben hep böyleydim."
    s "Sadece sen bunu yeni yeni görüyorsun."
    mc "Neyi görüyorum?"
    mc "Neden bahsediyorsun, Sayori?"
    s 1bq "Ehehe~"
    s 1ba "Bana illa söyleteceksin, değil mi [player]?"
    s "Sanırım bu sefer başka seçeneğim yok."
    s 1bc "İşin aslı şu ki..."
    s "Bütün hayatım boyunca ağır depresyon içindeydim."
    s 1bb "Bunu biliyor muydun?"
    s "Neden her gün okula geç kalıyorum sanıyorsun?"
    s "Çünkü çoğu zaman yataktan çıkacak bir sebep bile bulamıyorum."
    s 1by "Ne kadar değersiz olduğumu tamamen anladıktan sonra bir şey yapmanın ne anlamı var?"
    s "Neden okula gideyim?"
    s "Neden yemek yiyeyim?"
    s "Neden arkadaş edineyim?"
    s "Neden insanların enerjilerini ve ilgilerini boşu boşuna bana harcatayım ki?"
    s "Böyle hissediyorum."
    s "Bu yüzden herkesi mutlu etmek istiyorum..."
    s "Başkalarını endişelendirmeden."
    mc "..."
    "Şok içindeyim."
    "Nasıl cevap vereceğimi bile bilmiyorum."
    "Sayori bunca zamandır bunu benden nasıl saklı tutmuş olabilir?"
    "Onu düşünmememi cidden bu kadar çok mu istiyordu?"
    mc "... Neden, Sayori?"
    s 1bg "Ha?.."
    mc "Neden bana bundan hiç bahsetmedin?"
    mc "Dostun olarak ihanete uğramış gibi hissediyorum."
    mc "Bütün bunları bilseydim sana destek olmak için elimden geleni yapardım!"
    mc "Yapabileceğim çok fazla bir şey olmasa bile..."
    mc "Her günü senin için biraz daha güzel bir hâle getirmek için biraz daha çabalardım."
    mc "Arkadaşınım sonuçta!"
    mc "Tek yapman gereken şey bana bunu anlatmaktı!"
    s 1bk "Beni hiç anlamıyorsun, [player]."
    s "Sana bunları neden anlatmadım sanıyorsun?"
    s 1bd "Çünkü sana bunları anlatsaydım daha önemli şeyler yapmaktansa benimle ilgilenerek boşa çaba sarf etmiş olurdun."
    s "Ben önemsenmek istemiyorum."
    s "İnsanlar beni önemsemeye çalışınca bir tuhaf oluyorum."
    s 1ba "Kimi zaman iyi hissettiriyor."
    s "Ama aynı zamanda kafama sopayla vurulmuş gibi hissediyorum."
    s 4bq "Ahaha~"
    s 4ba "Bu yüzden diğerleriyle arkadaş olmanı bu kadar çok istedim..."
    s "Herkesin birbiriyle iyi geçinmesine, mutlu olmasına yardımcı olmak benim için en iyi şey."
    s 1bb "Ama sonra başka bir şeyin de farkına vardım."
    s "Kulüptekilerle arkadaş olup onlara yakınlaştığını görünce..."
    s 1bk "Kalbime bir mızrak saplanmış gibi hissediyorum."
    s "İşte bu yüzden."
    s "Bu yüzden evrenin bana sadece işkence çektirmek istediğini anladım."
    s 1by "Her yol acıdan başka bir şeye çıkmıyor."
    s "Ahaha~"
    mc "Haklısın, seni anlamıyorum..."
    mc "Hislerini hiç anlamıyorum, Sayori."
    mc "Ama anlamama gerek yok."
    mc "Acı çekmeni önleyecek şey neyse..."
    mc "Ben de onu yapacağım."
    s 1bd "Hayır, [player]."
    s "Yapabileceğin bir şey yok."
    s "Hiçbir şey yok."
    s "Yardımı dokunacak tek şey her şeyin eskisi gibi olması."
    s 1bk "Ama bencilce davrandım."
    s "Sana ne kadar rezil biri olduğumu gösterdim."
    "Sayori’nin yüzünden aşağı göz yaşları süzülüyordu."
    s 1bv "Bencil olduğum için edebiyat kulübüne katılmanı sağladım."
    s "Ve anlayamadığım bir şekilde kalbimin ağrımasıyla cezalandırıldım."
    s "Sen de şimdi buraya geldin ve senin de canının yanmasına sebep oldum."
    s 1bt "Ben zayıf ve bencil biriyim."
    s "Ben bu kadarım sadece."
    s "İşte bu yüzden bu cezaları kabulleneceğim."
    s 1bv "Çünkü her birini hak ediyorum!.."
    "Hiç düşünmeden bir kez daha Sayori’nin omuzlarını tutuyorum."
    "Bu kez ona sıkıca sarılıyorum."
    scene black with dissolve_cg
    s "Ş-Şey—"
    s "[player]..."
    mc "Sayori."
    mc "Bencil olup olmaman umurumda değil."
    mc "Beni kulübe katılmaya ikna ettiğin için gerçekten mutluyum."
    mc "Her gün seni görmek her şeyi yeterince iyi kılıyor."
    mc "Diğer herkesle arkadaş olmuşsam da bu sadece fazladan bir getiri."
    mc "Ama lütfen, sana ne kadar değer verdiğimi hafife alma."
    mc "Başka türlü düşünmeni istemezdim zaten."
    s "[player]..."
    "Sayori bana sarılmıyor."
    "Kollarımla onu sarmış olmama rağmen Sayori’nin kolları hâlâ iki yanında öylece duruyor."
    "Kulağımın yanında ağlamaya başlıyor."
    s "Hayır..."
    s "Bunu bana... yapma..."
    s "Lütfen bunu yapma..."
    s "[player]..."
    s "Ben..."
    "Sayori hıçkırıkları arasında zar zor konuşabiliyor."
    "Doğru şeyi yapıp yapmadığımı bilmiyorum."
    "Ama tek istediğim şey onu önemsediğimi bilmesi."
    mc "Madem kendine bencil demeye için el veriyor, benim de bencillik yapmamın sakıncası yok."
    mc "Ne pahasına olursa olsun, değişmesi gereken şeyi bulacağım."
    mc "Bu hislerin yok olmasını sağlayacağım."
    mc "Ve eğer yapmam gereken bir şey varsa..."
    mc "Söylesen iyi olur."
    mc "Söylemezsen kızarım."
    s "..."
    s "Bil... miyorum..."
    s "Bilmiyorum..."
    s "Bilmiyorum."
    "Sayori nihayet hafifçe kollarıyla beni sarıyor."
    s "Hiçbir şey bilmiyorum."
    s "Her şey çok korkutucu..."
    s "Hislerimin hiçbirini anlamıyorum, [player]..."
    s "Sadece acı çektiğim zamanlarda bir şeyler hissediyorum."
    s "Ama..."
    s "Bana sarılışın sıcacık..."
    s "... Bu da çok korkutucu."
    scene bg sayori_bedroom
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Sayori beni bırakıyor."
    "O beni bırakırken ben de onu bırakıyorum."
    mc "Festival yarın."
    s 1bk "Evet..."
    mc "Eğlenceli olacak, değil mi?"
    s "Evet."
    mc "Festivalin tamamını seninle geçirsem nasıl olur?"
    s 1bh "Ş-Şey..."
    s "A—"
    mc "Bunu ben istiyorum."
    mc "Yemin ederim."
    s 1bk "O..."
    s "O hâlde, güzel olur..."
    mc "Evet."
    "Sayori gözlerini siliyor."
    "Tüm günü burada geçirme imkânım olsa geçirirdim."
    mc "Onca gün varken bir bugün işim çıktı..."
    mc "Belki de iptal—"
    s 1bh "Hayır, yapma—!"
    s 1bg "Lütfen yapma..."
    s "Eğer yaparsan... seni gerçekten affetmem."
    mc "Ama..."
    mc "[ch4_name] evime gelmek üzere..."
    mc "En azından bize katılıp yardım etmek ister misin?"
    mc "Eğlenceli olur."
    "Şaşırtıcı bir şekilde, Sayori başını sallıyor."
    s 1bd "Üzgünüm."
    s "Gelmem bugün benim için iyi bir şey olur mu bilmiyorum."
    s "Anlıyorsun, değil mi?"
    mc "A..."
    mc "Bunu... anlaması benim için biraz zor."
    mc "Ama elimden geleni yapıyorum."
    s "Sorun değil."
    s "Bunu kafana takma o kadar."
    s 4ba "Yarın görüşürüz, tamam mı?"
    mc "... Pekâlâ."
    mc "Yarını dört gözle bekliyorum."
    scene bg residential_day with wipeleft_scene
    "Sayori’ye veda edip evinden çıkıyorum."
    "Geri dönerken yolda hâlâ huzursuz hissettiğimi fark ediyorum."
    "Ama [ch4_name] gelmek üzere olduğundan bu konuya kafa yormaya devam etmem zor..."
    "Sayori haklı sanırım."
    "Çok fazla endişelenmemeliyim, yarın kesinlikle harika bir gün geçireceğiz ne de olsa."
    "Beni bekleyen şeylere odaklanmalıyım!"
    call expression "ch4_exclusive_" + ch4_scene
    call ch4_end

    return


label ch4_exclusive_natsuki:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "Evde gergin bir şekilde Natsuki’yi bekleyerek sadece birkaç dakika geçiriyorum."
    "Zamanın nasıl geçtiğini anlamadan bana dış kapıda olduğuna dair mesaj atıyor."
    "Hiç gecikmeden kapıyı açıp onu içeri davet ediyorum."
    show natsuki 2bj zorder 2 at t11
    mc "..."
    n "N’aber?"
    mc "... Selam."
    "Ne beklediğimi bilmiyorum ama Natsuki’yi okul üniformasından başka bir şey giyerken görmek beni tamamen şaşırttı."
    "Üzerinde böylesine şirin giysiler olduğunu görünce okul üniforması bu giysilerin yanında çok uygunsuz duruyor."
    n 4bc "Of, daha en baştan işleri tuhaf hâle getirme!"
    n "Uzun bir gün olacak zaten, o yüzden sırf beni okul dışında görmeye alışkın olmadığın için garip davranma."
    n "Her neyse, içeri giriyorum."
    scene bg kitchen
    show natsuki 1bj zorder 2 at t11
    with wipeleft
    mc "Bakıyorum da pek çok şey getirmişsin..."
    "Natsuki’nin elinde, muhtemelen yiyecek malzemeleriyle dolu olan, büyük bir poşet var."
    n 2bj "Eh, bunca yolu gelip de mutfağında gerekli şeylerin olmadığını görmek istemedim."
    n "Senden istediğim her şeyi aldın, değil mi?"
    mc "Evet, aldım."
    "Natsuki dün benden evimde olmayan birkaç malzeme almamı istemişti."
    n 2bl "Güzel!"
    n "Görevini yerine getirmene sevindim."
    mc "Yani... Elbette."
    "Natsuki’nin ağzından iğneleyici bir şeyler çıkmasını beklerken birden böyle bir şey söylemesine şaşırdim."
    "Acaba okul dışındayken biraz daha farklı biri mi?"
    mc "Neyse, hadi mutfağa geçelim..."
    n 2by "Ne yani, bu ağır poşeti taşıma teklifinde bile bulunmayacak mısın?"
    n "Misafirperverliğin nerede, [player]?"
    mc "Hadi ama..."
    mc "Ne zamandan beri centilmenlik yapmam gerekti?"
    "Natsuki’nin bana uzattığı poşeti alıyorum."
    mc "Hığ—"
    mc "Bu çok ağır be—!"
    n 4bz "Ahaha!"
    n "Yol boyunca taşıdım onu."
    n 4bl "Etkilendin mi?"
    mc "Şimdi anlıyorum..."
    mc "Evet, etkilendim Natsuki."
    mc "Görünüşe bakılırsa seni hep hafife alıyorum."
    n 4by "Ehehe~"
    n "Çok küçük olduğum için, değil mi?"
    n 4ba "Hödük seni."
    "Natsuki göğsüme yumruk atıyor."
    mc "Hey, hey."
    mc "Boyunun bununla alakası yok."
    mc "Küçük olmaktan bu kadar çok mu nefret ediyorsun?"
    n 1bk "Ha?"
    n "Şey..."
    n 1bc "Nefret ettiğimden değil..."
    n "Ya, bazen insanlara boyuma kıyasla büyük işler yapabildiğimi kanıtlamayı seviyorum."
    n 1ba "Hem küçük olup hem de diğer insanlardan daha iyi olmak eğlenceli."
    n "Ama..."
    n 5bw "... Öf, boş ver!"
    n "Ne dedirtiyorsun sen bana?"
    n 5bq "Sırf okulda değiliz diye bana tuhaf şeyler söylettirebileceğini sanma!"
    n "Başlayacak mıyız artık? Sana öğretmem gereken tonla şey var."
    mc "Ahaha."
    n 5bn "Ne??"
    mc "İşte bu sana biraz daha yakışıyor."
    mc "Öyle sözünü esirgemediğin zaman daha eğlenceli oluyorsun."
    n 1bm "H-hey!"
    n "İşte {i}şimdi{/i} bana çocuk muamelesi yapıyorsun!"
    n "Sadece sana biraz daha iyi davranmaya çalışıyordum ben ya."
    n 1br "Yuri’ninki gibi olgun ve seksi bir vücudum yok diye bana öyle—"
    n 1bo "Ş-Şey—"
    "Natsuki söylediklerinin farkına varıyor ve kızarıyor."
    mc "Natsuki..."
    n 1bp "Unut gitsin!"
    n "Bir şey demedim!"
    mc "Senden özür dilemeliyim."
    n 1bh "Ha?"
    mc "Daha iyi davranmaya çalıştığın için minnettarım."
    mc "Ben de biraz daha duyarlı olmalıydım."
    mc "Hem ayrıca..."
    mc "Eğer öyle düşünüyorsan, bilmen gerekir ki vücudu senin gibi olanlardan hoşlanan tonlarca erkek var."
    n 1bq "A..."
    n "Bunu... sen nereden biliyorsun ki?"
    mc "Bu konuda güven bana."
    n "..."
    n 5bx "... İğrenç."
    mc "Hey!"
    mc "Bana mı dedin onu?"
    n 5bw "Başka kime olacak?"
    mc "Of..."
    mc "Hadi başlayalım artık."
    n 2bl "Ahaha!"
    n "Bir kız sana iğrenç deyince nasıl da moralin bozuluyor."
    n 2bd "Sonunda zaafını buldum, [player]."
    "Natsuki sinsi sinsi gülümsüyor."
    mc "Ya bir git..."
    "Natsuki hakaretlerine devam ederse karşılık vermememin imkânı yok."
    "Ama Natsuki yeteri kadar tatmin oluyor ve en sonunda poşetinin içindekileri çıkarmasıyla işe başlıyoruz."

    scene bg kitchen
    with wipeleft_scene
    "Çok geçmeden mutfak savaş alanına dönüyor."
    "Tüm tezgâhların üstü kaşıklar, kirli kâseler, yere dökülen sıvı ve torbalarla dolu."
    "Mikser gerekli tüm hamuru hazırlayacak kadar büyük olmadığından işlemi birkaç kez tekrar etmek zorunda kalıyoruz."
    "Bu sırada, Natsuki kıymetli görevini berbat etmediğimden emin olmak için her hareketime karışıyor."
    show natsuki 2bk zorder 2 at t11
    n "[player], gıda boyasını nereye koydun?"
    n "Hamuru birazdan fırına atacağım, tepsileri doldurmam gerekli."
    mc "Galiba hâlâ masanın yanındaki poşetin içinde."
    mc "Boyayı ne yapacaksın?"
    n 4bl "Hamuru boyayacağım tabii ki!"
    n 4bj "Her tepsiyi farklı renge boyayacağım."
    n "Böylelikle, tatları farklı olmasa da herkes hâlâ en sevdiği rengi seçerek memnun olacak."
    mc "Ah, ne şirin bir fikir."
    mc "Kremayla ona benzer bir şey yapacak mıyız?"
    n 4bk "Yapmak istiyor musun?"
    mc "A..."
    mc "Bana mı soruyorsun?"
    mc "Benim için çok fark etmez..."
    n 1bm "Hadi ama..."
    n "Bu işi hiç hevesle yapmıyorsun!"
    n "Biraz eğlenmeyi deneyemez misin?"
    mc "Eğleniyorum..."
    "Natsuki benden ne duymak istiyor cidden emin değilim."
    "Bu sırada, onu hamuru küçük kâselere dağıtıp her birine birkaç damla gıda boyası katarken görüyorum."
    mc "Ah, harika görünüyor."
    n 2bj "Gördün mü?"
    n "Bir şeyler pişirmek talimatları izlemekten ibaret değil."
    n "Asıl eğlendiğin ve yaratıcılığını kattığın kısım pişireceğin şeyin sunumudur."
    n "İnsanlar yaptığın şeye bakınca gözleri parlıyorsa, yaptığın her şeye o kadar çok değiyor ki..."
    mc "İlk geldiğim gün yaptıkların gibi mi?"
    "Natsuki’nin kedi şeklindeki kapkeklerini sunuşunu ve Sayori ile Monika’nın yüzlerindeki mutlu ifadeyi hatırlıyorum."
    "Acaba ben de Natsuki’yi öyle gururlandırabilir miyim?"
    mc "Evet..."
    mc "O hâlde belki ben de gıda boyası kullanabilirim."
    n "Galiba anlamaya başlıyorsun."
    n "Gıda boyasıyla uğraşmadan önce kremayı karıştırmayı bitir de önce."
    mc "Tamam, az kaldı."
    "Hamur için mikseri kullandığımızdan krema karışımını kocaman bir kâseye döküp çırpma teliyle karıştırmak zorunda kalıyorum."
    n 4bc "Ha?"
    n "Krema hâlâ lapa gibi!"
    n "Karıştırdığına emin misin sen?"
    mc "Yani, evet..."
    mc "Biraz daha sürecek sadece."
    n 4bg "Of, bu gidişle tüm gece burada duracağım."
    n "Ver şunu."
    "Natsuki çırpma telini benden alıyor diğer eliyle kâseyi geriye yatırıyor."
    n 4be "Buna şöyle... sağlı sollu... girişeceksin!"
    "Birkaç saniye sonra kremanın kıvamı yerine gelmişti bile."
    n 4ba "Gördün mü?"
    "Natsuki, yaptıklarının sonucunu vurgularmışçasına, bir parmağını kremaya sokup o parmağı ağzına götürüyor."
    "Ben de isteksizce aynı şeyi yapıyorum."
    n 1bh "Hey!"
    "Natsuki birden bileğimi tutuyor."
    n 4bh "{i}Senin{/i} pis parmaklarını benim kremamın içinde istemiyorum."
    mc "Senin kreman, ha?"
    mc "Bütün her şeyi kimin yaptığını unutuyorsun galiba?"
    "Karşı koymaya başlıyor, parmağımı kâseye yakınlaştırmaya çalışıyorum."
    n 4by "Bir dahakine sana sağlı sollu girişirim bak!"
    mc "Hele bir dene!"
    "Parmağımı kremaya değdirecek kadar yakınlaşıyorum."
    "Natsuki’nin çekiştirmelerine rağmen, zafer kazanmışım edasıyla parmağımı kremaya daldırıp krema alıyorum."
    mc "Ah—!"
    "Natsuki’nin güçlü çekiştirmesi tökezlememe sebep oluyor ve bununla birlikte o da tökezliyor."
    n 1bx "İğrenç!"
    n "Yüzüme bulaştırdın!"
    mc "Kimin suçu bu acaba?!"
    "Natsuki’nin yanağında büyük bir krema damlası var."
    n 1bw "Nnn—"
    "Dilini o damlaya uzatmaya çalışıyor ama damla çok uzakta kalıyor."
    n 1br "Offf..."
    n "Biliyor musun?"
    n 4bd "Sen kaşındın!"
    "Natsuki yanağındaki damlayı parmağıyla siliyor ama hemen sonra o parmağını yüzüme sokmaya çalışıyor."
    mc "Çok beklersin—!"
    "Ben daha hızlıyım."
    "Elini yüzüme yaklaştıramadan bileğini yakalıyorum."
    "Natsuki diğer elini kullanarak karşı koymaya çalışıyor ama o elini de yakalıyorum."
    $ persistent.clear[4] = True
    scene n_cg3_base
    show n_cg3_exp1
    show n_cg3_cake
    with dissolve_cg
    n "Ahahaha! Kes şunu!"
    mc "Bana iğrenç dediğin için özür dilemeden olmaz!"
    n "Tamam, tamam!"
    n "Sana iğrenç dediğim için üzgünüm."
    n "Bunu gerçekten demek istemediğimi biliyorsun."
    n "Sadece senin tepkini görmek eğlenceli oluyor."
    n "... Sen bana bunu hep yapıyorsun!"
    n "Sırf tepki göstermem için aptal aptal şeyler söylüyorsun."
    n "Kızlarla böyle dalga geçmemelisin."
    mc "Demek öyle?"
    mc "Bu durumda bunu da yapmamalıyım..."
    show n_cg3_cake at cgfade
    hide n_cg3_cake
    "Natsuki’nin parmağını tutup ağzıma götürüyor, kremayı yalıyorum."
    show n_cg3_exp1 at cgfade
    show n_cg3_exp2 at cgfade
    hide n_cg3_exp1
    n "N-N-Ne—?"
    n "S-Sen cidden az önce—"
    n "Ş-Şey—"
    "Natsuki o kadar şaşırdı ki bana nasıl kızacağını bile anlayamaz hâlde."
    "Yüzü kıpkırmızı."
    hide n_cg3_exp2
    n "[player]..."
    n "Böyle bir şeyi bir kıza yapmamalısın... eğer ondan hoşlanmıyorsan..."
    n "Bunu biliyorsun... değil mi?"
    mc "..."
    "Bana sorduğu soru nasıl bir şey öyle?"
    "Olayların gidişatı nasıl bu kadar çabuk değişti?"
    mc "Ben..."
    "Natsuki sessizce bana bakıyor."
    "Onun hızlı nefes alış verişini fark ediyorum."
    "Neden başım dönmeye başladı?.."
    n "Ha?!"
    scene bg kitchen with dissolve_cg
    "Birden yangın alarmı çalıyor."
    "Natsuki fırına doğru koşuyor."
    mc "Bir şey mi yanıyor?"
    mc "Kapkekleri daha koymadın sanıyordum."
    show natsuki 1bw zorder 2 at t11
    n "{i}*Öhö öhö*{/i}"
    n "Şu işe bak..."
    n 1bb "Fırının içinde kirli bir tepsi bırakmışsın, aptal!"
    n "Böyle bir hatayı nasıl yapabilirsin?"
    mc "Fırını açmadan önce kontrol etmeliydin!"
    n 1bs "Kendi hatalarını bana yıkma!"
    n "Of..."
    "Natsuki, fırından kararmış tepsiyi bir fırın eldiveni yardımıyla çıkarıyor."
    "Tepsiyi ocağın üstüne koyuyor."
    "Biraz sonra yangın alarmı duruyor."
    n 1bq "Her neyse..."
    n "Ben... şunları fırına koyayım."
    mc "Evet..."
    "Az önceki anın gerginliğinden ikimiz de hâlâ kurtulamadık."
    "Ama o an çoktan kayboldu."
    "Natsuki tepsileri fırına yerleştirirken onu izliyorum."
    "Sonra, isteksizce çırpma telini elime alıp hiçbir şey olmamış gibi kremayı çırpmaya devam ediyorum."

    scene bg kitchen
    show natsuki 4bz zorder 2 at t11
    with wipeleft_scene
    n "Ahh, çok güzel kokuyor!"
    "Kapkekler fırından çıkarılmaya hazır."
    "Natsuki fırının kapağını açar açmaz odayı tatlı bir koku sarıyor."
    n 4bl "Şunların şirinliğine baksana!"
    "Natsuki gururla her bir tepsideki farklı renkli kapkekleri gösteriyor."
    mc "Kremayı ekleyince çok daha iyi görünecekler."
    n 2ba "Bunu {i}bana{/i} söylemene gerek yok!"
    n "Süsleme malzemelerini getirdim. Umarım ortaya yaratıcı bir şeyler çıkarabilirsin."
    n "Al, kremayı bu torbalara doldur."
    "Natsuki bana birkaç plastik torba uzatıyor."
    n 2bj "Elimdeki bu ağızlıklarla daha güzel ve ponçik olacaklar."
    n "Hele şu var ya, çiçek bile yapabiliyor!"
    n "Bu sefer onu kullanmayacağız ama galiba."
    mc "Bu ne için?"
    "Ucu diğerlerinden çok daha ince olan bir ağızlık elime alıyorum."
    n 4bk "O bayağı ince. Çizgili veya başka türde desen yapmak için kullanabilirsin."
    n "Bir pastanın üzerine bir şey yazmak için de kullanabilirsin."
    n "‘İyi ki doğdun’ gibi falan."
    mc "Ha, anladım..."
    mc "Aslında aklıma bir fikir geldi."
    n "Ha?"
    mc "Hazırlandığımız şey bir edebiyat etkinliği, değil mi?"
    mc "Her bir kapkekin üzerine farklı bir kelime yazarsak biraz daha edebiyat temalı bir şey yapmış oluruz."
    mc "İnsanların sevdikleri sözcüğün yazılı olduğu kapkeki seçmelerini izlemek eğlenceli olurdu."
    n 1bq "Of..."
    mc "Hm?"
    n "Gerçekten aptalca bir şey demeni bekliyordum..."
    n 1bs "Ama bu aslında... oldukça şirin bir fikir..."
    mc "Ahaha."
    mc "Belki de senden ilham alıyorumdur."
    n 5bh "N-Ne demek oluyor bu?"
    n "Ben şirin değilim!"
    mc "Hadi ama..."
    mc "Şu an okulda değiliz, kimse seni yargılamıyor."
    mc "Bunları giyip böyle davrandıktan sonra şirin olmadığını düşünmemi bekleyemezsin."
    n 5bs "Ş-Şey..."
    "Natsuki’nin sesi azalıyor."
    n "Aynısı senin için de geçerli..."
    mc "Ha?"
    mc "Bir şey mi dedin?"
    n 1bw "H-Hayır, yok bir şey!"
    n "Hadi krema işini halledelim!"
    "Natsuki hızlanıyor ve her bir torbaya bir ağızlık takıyor."
    n 1bh "Yapacak çok şey var, boşa zaman kaybetmemeliyiz!"
    n "Al şunu, sana nasıl yapılacağını göstereyim."
    "Natsuki az önceki olayı düşünmeme fırsat vermeden hızlıca ilerliyor."
    "Bana kremayı nasıl sıkacağımı gösterdikten sonra ikimiz de işe koyuluyoruz."

    scene bg kitchen with wipeleft_scene
    "Nihayet her şeyi bitirdiğimizde, Natsuki ortaya çıkardıklarımızı hayranlıkla izlemek için hepsini yan yana koyuyor ."
    show natsuki 4bl zorder 2 at t11
    n "Bir arada ne kadar güzel görünüyorlar, baksana!"
    mc "Evet, ne güzeller, değil mi?"
    n 1bm "Uu... Keşke şimdi birini yiyebilseydim!"
    mc "Yiyememen için hiçbir sebep yok ama, değil mi?"
    mc "Bir zararı olmaz bence."
    n 1bc "Şey, evet ama..."
    n "Bugünün akşam yemeğini babam yapacak, o yüzden iştahımı korumalıyım."
    mc "Ahaha."
    mc "Sayori’ye kalsa tam tersi olurdu."
    mc "Burada olsaydı çoktan on kapkeki hüpletmişti."
    mc "Ve yine de akşam yemeğini yerdi."
    n 4bg "Hadi ama, bu çok sağlıksız!"
    n 4bs "Ayrıca, yemeği babam pişirdiğinde yiyebildiğim kadar yemem gerekli..."
    n 4bq "... Aman, neyse!"
    n 4bc "Manga okumaya da vaktimiz kalır diye umuyordum ama akşam yemeğine yetişmem lazım..."
    mc "A, hemen şimdi mi?"
    mc "Yazık oldu."
    n 1bg "Bunun suçlusu sensin, yavaş çalıştın çünkü!"
    n "Bunu düşünmen gerekirdi."
    n "Böyle bir şeye her zaman fırsat olmaz."
    mc "Of..."
    "Her zamanki gibi Natsuki bütün suçu bana yıkıyor."
    n 2bk "Kapkekleri yarın getirebilirsin, değil mi?"
    n "Sayori’yle birlikte tek seferde götürebilirsiniz herhâlde."
    mc "Evet, getirebilirim."
    mc "Ve merak etme, ona kapkek vermem."
    n 2ba "Ahaha."
    n "Keşke Sayori seni dinlediği kadar beni de dinlese."
    mc "A..."
    mc "Evet."
    show natsuki zorder 1 at thide
    hide natsuki
    "Bugün Sayori’yle yaptığımız konuşmayı düşünüyorum tekrar."
    "Çok çaresiz hissettim."
    "Sayori beni hep dinliyor, evet ama o an beni hiç dinleyememiş gibiydi."
    show natsuki 4bl zorder 2 at t11
    n "Tamam, her şeyi topladım."
    n "Ellerine sağlık!"
    mc "Senin de."
    mc "Seni kapıya geçireyim... o hâlde."

    scene bg house with wipeleft_scene
    "Natsuki çıkmaya hazır bile."
    "Öğleden sonrası bir anda olup bitmiş gibi hissediyorum."
    "Onu da geçtim..."
    "Ona istediğim gibi yakınlaşma fırsatı yakaladım mı ki?"
    show natsuki 1bh zorder 2 at t11
    n "Şey..."
    n "Ben gidiyorum..."
    n 1bq "Yardımın ve her şey için teşekkürler..."
    n "Yarın görüşürüz."
    mc "Dur, Natsuki."
    n 1bh "Ha?"
    mc "Az önce demiştin ya... böyle şeylere her zaman fırsat olmaz diye."
    mc "Hiç öyle olması gerekmiyor!"
    mc "Ben bugün eğlendim."
    mc "Bana bir şeyler pişirmenin ne kadar eğlenceli olabileceğini gösterdin, tıpkı istediğin gibi."
    mc "Ama onun yanı sıra..."
    mc "Bana istediğin zaman uğrayabilirsin, tamam mı?"
    mc "Mümkünse, bu şekilde daha fazla zaman geçirmek istiyorum."
    mc "Eğer manga okumak istersen veya dışarı bir yere gitmek istersen—"
    n 1bm "Şey—"
    n "Sahiden... mi?"
    "Natsuki bana gergin bir şekilde bakıyor, yüz ifadesini saklamak istercesine."
    mc "Evet."
    mc "Seninle daha fazla zaman geçirmek istiyorum."
    n 1bq "[player]..."
    n "Sadece bu işi bir an önce bitirmeyi önemsediğini düşünmüştüm..."
    n 1br "Uu..."
    n 1bn "Bugün bu kadar erken gitmek zorunda olduğum için üzgünüm."
    n "Gitmeyi cidden istemedim!"
    n "Elimde olsa... burada daha uzun süre kalırdım."
    n "Ben de senin gibi düşünüyorum..."
    stop music fadeout 2.0
    show natsuki 1bi at face with dissolve
    "Natsuki birden bana yakınlaşıyor."
    mc "Dur, Natsuki—"
    "Benden birkaç adım ötede duran Natsuki yüzüme bakıyor."
    "Parmaklarının bana tutunurmuşçasına gömleğimin yanlarını çekiştirdiğini hissediyorum."
    "Gözlerim onun hafif aralık olan dudaklarının eşlik ettiği pembe renkli yanakları ve aynı renkteki gözlerinden başka bir şey görmüyor."
    "Neler oluyor?.."
    "Onun yumuşak nefes alıp verişlerini üzerimde hissederken başım dönüyor."
    n 1bh "Bir süredir..."
    n "Hissediyordum da..."
    n 1bo "—!!"
    show natsuki zorder 2 at t11
    "Natsuki aniden geriye sıçrıyor."
    n "S-Sayori?!"
    mc "Ha?!"
    show natsuki zorder 2 at t22
    show sayori 1bl zorder 3 at f21
    s "A..."
    s "S-Selam, [player]..."
    mc "Sayori—!"
    mc "Biz az önce—"
    s 1bq "Ehehe~"
    s "Önemli değil, [player]."
    s 1ba "Sadece selam vermek için uğramıştım~"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 5bq "Ş-Şey..."
    n "Şey..."
    n 5bw "B-Biraz daha erken gelmeliydin!"
    n "Ben şimdi gidiyorum da..."
    show natsuki zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "Ya, cidden mi?"
    s "Çok kötü oldu..."
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 2bq "Evet, şey..."
    n "Yarın festivalde görüşeceğiz zaten, sorun yok."
    n 2bb "Festivalden önce bir tane bile kapkek yemek yok!"
    n "Neyse, görüşürüz!"
    show natsuki at lhide
    hide natsuki
    "Telaşlandığı bariz olan Natsuki aceleyle yola koyuluyor, Sayori de ona el sallıyor."
    return

label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "Evime yaklaşırken bana bir anlığına panik hissettiren bir şey görüyorum."
    mc "Yuri—?"
    show yuri 2bq zorder 2 at t11
    y "A..."
    y "Şükürler olsun..."
    mc "Biraz erken geldin..."
    mc "Özür dilerim, evde değildim!"
    mc "Çok bekledin mi?"
    y 1bf "Hayır, az önce geldim."
    y 1bh "Ama zili çaldığımda kimse cevap vermeyince çok telaşlandım..."
    mc "Bana mesaj atabilirdin."
    mc "Bilseydim sana cevap yollar, aceleyle eve gelirdim."
    y 2bv "A... Sanırım haklısın..."
    y "Nedense... bunu düşünmedim."
    "Bunu yapmak akla ilk gelen şey olmalı ama daha fazla üstelememeye karar veriyorum."
    mc "Her neyse... Hadi içeri geçelim."
    mc "Bakıyorum da yanında pek çok şey getirmişsin."
    y 1ba "Doğru."
    y "Peki sen almanı istediğim her şeyi alabildin mi?"
    mc "Evet, hemen hemen."
    mc "En azından yanlış bir şey almadığımı umuyorum."
    y "Sorun olmayacağına eminim."
    scene bg bedroom with wipeleft
    "Yuri’yi odama götürüyorum."
    "Yuri’nin ilk yaptığı şey merakla etrafa bakmak oluyor, ki bu da beni geriyor."
    show yuri 2bm zorder 2 at t11
    y "Çok temiz..."
    mc "Ahaha..."
    mc "Sen gelmeden önce temizledim..."
    y 2ba "Çok düşüncelisin."
    mc "Şey, ne demek..."
    mc "Seni odam dağınıkken ağırlasam epey utanırdım."
    y 1ba "Hmm..."
    y "Yani, temizlik yapmayı severim ben..."
    y "Sana odanı temizlemene seve seve yardım ederdim."
    mc "A—"
    mc "Bu çok daha utanç verici olurdu!"
    show yuri 1be
    mc "Dur, oraya bakma—!"
    "Yuri’nin çekmecelerimden birini açmak üzere olan bileğini tutuyorum."
    y 3bn "Ş-Şey..."
    y "Özür dilerim!.."
    y 4bb "Nedense düşüncesizlik ettim..."
    y "Dalmışım!"
    mc "Sorun değil, sorun değil..."
    "Yuri’nin bileğini bırakıyorum."
    show yuri 1bl
    "Yuri iki elini de bir yere kaçmamalarını istermişçesine dizlerinin önünde buluşturuyor."
    mc "Şey, a..."
    mc "Başlasak mı... artık?"
    y 2bu "A..."
    y "Tabii..."
    y 2bf "Hm, yardım edebileceğin birkaç şey planladım..."
    y "Dekorasyonlar ve ortam iyileştirmeleri."
    mc "Ortam iyileştirmeleri mi?.."
    y 1ba "Şey, yani..."
    y "Işıklandırmalar, aromaterapi mumları..."
    mc "Vay be."
    mc "İşleri bu kadar ileri götürmeyi planladığını bilmiyordum."
    y 1bc "Elbette."
    y "Konuklarımızı uzak bir yere götürmeye yardımcı olmak istiyorum."
    y 1ba "Gerçi birçoğu meraktan uğrayacaktır..."
    y 1bj "Ve... kapkekler için belki..."
    y 1ba "İnsanlara vazgeçemeyecekleri bir tecrübe yaşatmaya kararlıyım."
    mc "Bu harika."
    mc "Ne kadar ciddi biri olduğunu unutuyorum bazen."
    y 1bt "A—"
    y 2bt "Ciddi mi?.."
    mc "Bence bu durum en iyi böyle ifade edilir."
    y "Bu... kötü bir şey mi?"
    mc "Hayır, hiç de bile."
    mc "Bu, sevdiğim özelliklerinden hatta."
    y 3bu "Ö-Öyle mi?.."
    y "Rahatladım..."
    y "Biraz da sevindim..."
    mc "Evet, o kadar gergin olmana gerek yok."
    mc "Biraz gevşeyebilirsin."
    y 3bl "Gevşemek..."
    y 1bf "Gevşemek için birkaç şey getirmiştim."
    y "Şiir etkinliği için kullanacaktım onları..."
    mc "Hadi ya? Ne gibi?"
    y "Bakayım..."
    "Yuri çantasını karıştırıyor."
    "İçinden birkaç adet mum ve silindirik, ahşap bir nesne çıkarıyor."
    y "Buraya gelirken biraz alışveriş yapmıştım da, o yüzden çantamda bunlar da var."
    y "Pencereyi siyah kâğıtla kaplayıp odayı mumlarla aydınlatmayı düşünüyordum."
    y 1ba "Bence bu inanılmaz olurdu. Sence de öyle olmaz mıydı?"
    mc "Evet, harika olurdu."
    mc "O ahşap şey ne peki?"
    y 1bf "A, bu mu?"
    y "Bu, esanslar için bir koku yayıcı."
    y "Aromaterapiyle aran nasıl?"
    mc "Hiç aram yoktur..."
    y 1ba "A, demek öyle."
    y "Bu, olumlu bir atmosfer oluşturmak için en sevdiğim yöntemlerden biridir."
    y "Seçtiğin esanslara veya bitkilere göre bulunduğun yerin havasını değiştirebilirsin."
    y "Hatta, havanın vücuduna nüfuz ettiğini bile hissedebilirsin."
    y 3bm "Sakinleşme, pozitif enerji, romantizm, derin düşünme..."
    y "Neredeyse büyü gibi."
    show yuri 3ba
    "Yuri silindiri alıp en altındaki düğmeye basıyor."
    "Kısa süre içinde silindirin üstündeki küçük delikten ince bir buhar hüzmesi yayılmaya başlıyor."
    mc "Vay canına, harika kokuyor."
    mc "Hangi esansı seçtin?"
    y 1ba "Bu, yasemin esansı."
    y "Hafif tatlı ve çiçeğimsi kokuyor, değil mi?"
    mc "Evet, güzel tanımladın."
    y 1bb "Etkinlik için yasemini tercih ettim çünkü gevşeme hissinden daha fazlasını sunuyor."
    y "Yasemin duygularını harekete geçirir ve onların vücudunda dolaştığını hissetmeni sağlar."
    y 1bu "İçin kıpır kıpır olur ve kalp atışın daha da hızlanır."
    y 1ba "Sence de şiirlerimizi paylaşacağımız an için mükemmel olmaz mı bu?"
    mc "Kulağa uygun geliyor..."
    mc "Ama bu konuda epey bilgili görünüyorsun, o yüzden sen ne dersen kabulüm."
    show yuri 1bc
    "Yuri zarif bir şekilde gülümsüyor. Eğlendiği yüzünden okunuyor."
    "Tekrar çantasına uzanıp içinden birkaç makara ince kurdele çıkarıyor."
    show yuri 1ba
    mc "Bunlar ne için?"
    y 1bf "Şey..."
    y "Almanı istediğim origami kâğıdını aldın mı?"
    mc "Evet, şuraya koydum..."
    y "Kâğıdı origami yapmak için kullanmayacağız."
    y "Yapmak istediğim şey her kâğıda farklı bir kelime yazmak."
    y "Yaklaşık yüz tanesine ihtiyacımız olacak."
    mc "Hadi ya?"
    mc "Bunlar ne için kullanılacak?"
    y 2bf "Kurdele parçaları kesip parçaları sınıfın girişine asacağım."
    y "Ardından kâğıtları kurdelelere tutturarak giriş için bir perde hazırlamış olacağız."
    y 2bm "Bu güzel olmaz mıydı?"
    y "Bu aynı zamanda odanın yanından geçenlerin de dikkatini çeker..."
    y 2ba "Merak edip içeri girenler olacaktır."
    mc "Bu gerçekten yaratıcı bir fikir!"
    mc "Bu konuda bu kadar iyi olabileceğini hiç düşünmemiştim, Yuri."
    y 4ba "Öyle... mi?"
    y "Yani, sanırım biraz ciddileşebiliyorum... senin deyiminle."
    y 3bu "Uhuhu."
    "Yuri, yanakları kızarmış bir şekilde kıkırdıyor."
    "Bana mı öyle geliyor yoksa Yuri ikimiz baş başayken daha mı rahat?"
    "Veya belki de sevdiği bir şeyi paylaşmanın verdiği heyecanın etkisidir bu."
    y 1ba "Şu tahta kalemini al [player]."
    y "İstediğin karakteri yazabilirsin."
    y "Kurdeleleri kesmeyi bitirdikten sonra sana yardım ederim."
    mc "A, tamam."
    "İkimiz de yere oturup işe koyuluyoruz."
    "Her bir kağıda farklı bir karakter çiziyor, kötü el yazıma rağmen olabildiğince iyi yazmaya çalışıyorum."
    "Yuri kırmızı kurdele makarasından istediği uzunlukta bir parça belirliyor."
    "Ardından bir kez daha çantasına elini sokuyor ve içinden bir cep bıçağı çıkarıyor."
    mc "Hm?.."
    "Bıçağın tuhaf bir güzelliği var."
    "Bıçağın gümüş kabzasına birbirine geçmiş dalgaların olduğu bir desen işlenmiş."
    "Bıçağın yüzeyi hafif mavi tonda."
    mc "Bu öyle sıradan bir cep bıçağı değil..."
    mc "Epey şık duruyor."
    y 4bb "Ş-Şey..."
    y "Şey..."
    "Utanan Yuri kafasını çeviriyor."
    mc "Ne oldu?"
    y "Garip olduğunu düşüneceksin..."
    mc "Yuri, seni yargılamak için hiçbir sebebim yok."
    mc "Herkesin zevkleri farklı ne de olsa."
    y "Garip bulmayacağına söz verirsen..."
    mc "Söz veriyorum."
    y 2bi "Pekâlâ..."
    y "Doğrusu, bıçaklara ilgim var..."
    y "Onlar çok... güzeller..."
    y 2bv "E-Elimde değil!"
    y "Nasıl açıklanır bilmiyorum..."
    y "El işçiliği ve tehlike hissinin birleşimi belki..."
    y 4bb "Ha, ne diyorum ben?.."
    y "Lütfen bu yüzden tuhaf olduğumu düşünme..."
    mc "Ahaha."
    y "Bana gülüyorsun..."
    mc "Hayır, sana gülmüyorum."
    mc "Bunları paylaşırken bu kadar gerginleşmen çok komikti."
    mc "Bu... Şey, ilginç bir ilgi alanı sanırım."
    mc "Ama bence sana yakışıyor."
    y 2bt "Bana yakışıyor mu?.."
    mc "Evet... Enteresan bir ilgi alanı. Ahaha."
    mc "Ayrıca, itiraf etmeliyim ki, o bıçak bir hayli havalı duruyor."
    y 2bu "Gerçekten öyle, değil mi?.."
    "Yuri bir kez daha sakin bir yüz ifadesiyle bakıyor."
    y 1ba "Tutmak ister misin?"
    mc "Olur, bir bakayım."
    "Yuri, bıçağı kabzası bana dönük bir şekilde dikkatlice uzatıyor."
    "Bıçağı elime alıyorum ve döndürüyorum."
    "Oldukça ağır ve sağlam bir bıçak."
    "Böyle bir bıçak nereden alınabilir ki?.."
    "Keskinliğini merak ettiğimden işaret parmağımı bıçağın ucuna dokunduruyorum."
    mc "Uf—!"
    y 3bn "[player]—!!"
    y "Neden yaptın bunu?!"
    mc "Bu kadar keskin olmasını beklemiyordum!.."
    mc "Ucuna çok az dokunmuştum oysaki."
    y "B-Benim suçum!"
    y 3bo "Seni uyarmalıydım..."
    y "Bu bıçak son derece keskin..."
    y "İnsan cildini kâğıt gibi kesebilir."
    y 2bv "Eyvah..."
    "Parmağımın kenarından aşağı küçük bir damla kan akıyor."
    "Yuri elimi tutup yarama yakından bakıyor."
    y 2bt "A..."
    "Gözleri yaramın üstünde ve telaşlandığı apaçık ortada."
    mc "Miden bulandıysa hemen yıkayım—"
    mc "A-Ah!"
    "Yuri ansızın parmağımı ağzına sokuyor ve yarayı yalıyor."
    "Dilinin parmağımın etrafında dolaştığını hissediyorum."
    "Ürküp içgüdüsel olarak elimi çekiyorum."
    y "Ş-Şey..."
    y 3bo "L-Lütfen affet beni!"
    y "Düşünmeden yaptım!"
    y 4bc "Ben..."
    "Yüzü kıpkırmızı olan Yuri başını yere eğiyor."
    mc "Yuri..."
    y "Bu, hayatımda yaptığım en utanç verici şey..."
    y "Böyle bir şeyi nasıl yapabilirim??"
    y "Özür dilerim, özür dilerim..."
    mc "A..."
    "Evet, tuhaf bir şeydi ve şaşırdım..."
    "Ama yardım etmeye çalışıyordu, değil mi?.."
    mc "Yuri, bence aşırı tepki veriyorsun..."
    y "Uuu..."
    "Yuri başını kaldırmıyor."
    "Ya gün boyunca bunun etkisinden çıkamazsa?"
    mc "Pekâlâ, bak şimdi..."
    "Bu aptalca bir şey olabilir ama yine de yapıyorum."
    "Karşılığında ben de gidip Yuri’nin işaret parmağını yalıyorum."
    show yuri 3bn at h11
    y "[player]—!!"
    y "B-Bunu yaptın mı cidden?"
    mc "Ş-Şimdi eşitlendik..."
    y 3bv "..."
    "Yuri bana yanlış bir şey yapmışım gibi bakıyor."
    mc "Ahaha..."
    mc "Bunun kötü bir fikir olduğunu biliyordum..."
    "Yasemin esansının tatlı aroması olmasaydı eğer ortam epey gergin olurdu."
    y 1bu "Çok tuhafsın, [player]."
    "Yuri utangaç bir şekilde kıkırdıyor."
    mc "Hm?.."
    "Yuri {i}bana{/i} mı tuhaf diyor?"
    "Buna verebileceğim bir karşılığım yok..."
    y 1bf "Yara bandı nerede?"
    mc "A..."
    mc "Gerek yok aslında."
    mc "Küçük bir kesik sadece."
    mc "Bak, kanama durdu bile."
    y 1ba "Anlıyorum..."
    y "Sevindim."
    "Gerginlik çabucak geçti."
    "İkimiz de kendi işlerimize geri döndük."
    "Yuri’nin bıçağının kurdeleyi havayı kesermiş gibi kesmesini izliyorum."
    "Ben de o sırada yazı yazmaya devam ediyorum."

    scene bg bedroom with wipeleft_scene
    "Kâğıtları kurdelelere tutturmayı bitirdikten sonra hepsini yan yana koyuyoruz."
    "Beklediğimden daha iyi görünüyor. Bir kapı perdesi olarak çok etkileyici duracağına eminim."
    mc "Harika görünüyor."
    mc "Bunu iyi düşündün, Yuri."
    show yuri 1bq zorder 2 at t11
    y "A, teşekkürler..."
    y "Bu, internette gördüğüm bir şeydi."
    y 1ba "Bir sonraki göreve geçmeye hazır mısın?"
    mc "Evet, hadi yapalım."
    mc "Aklında ne var?"
    y "Bir pankart yapmak istiyorum."
    y "Bu yüzden senden tablet boyaları almanı istedim."
    mc "Ah, tabi ya."
    "Yuri’nin almamı istediği şeylerden biri de tablet sulu boya setiydi."
    y 1bf "Her bir tableti koymak için içi su dolu altı bardağa ihtiyacımız olacak."
    y "Zahmet olmazsa hepsini getirebilir misin?"
    mc "Tabii."
    mc "İçi su dolu altı bardak..."
    mc "Birazdan gelirim."
    y 1ba "Çok teşekkürler."
    y 2bf "A, suyu az doldurman yeterli."
    y "Bardakları çok doldurursan boya çok seyrekleşir."

    scene bg bedroom with wipeleft_scene
    "Yuri’nin tavsiyesine uyarak normal boyutlu bardaklar kullanmaktansa küçük banyo bardaklarından kullanmaya karar veriyorum."
    "Boyalar başka yere dökülmesin diye bardakları tepsiye koyuyorum ve odama getiriyorum."
    mc "Yuri?"
    show yuri 1bd zorder 2 at t11
    y "Evet?"
    "İçeri girdiğimde Yuri’yi elbisesinin yukarı kıvrılmış olan kolunu çabucak aşağı indirirken görüyorum."
    mc "A, hiç..."
    mc "Yüzün biraz kızarmış."
    mc "Burası fazla mı sıcak?"
    y 3bq "A—"
    y "Yo, hiç de bile!"
    y "Herhangi bir sorun yok..."
    y "Boyaları karıştıralım hadi."
    "Yuri çabucak elimden tepsiyi alıyor ve tabletleri paketlerinden çıkarıp bardaklara bırakıyor."
    y 1ba "Şimdi..."
    y "Güzel görünecek basit bir şey yapmayı düşündüm."
    y "Pankartın üzerini bir renk geçişiyle kaplamak istiyorum..."
    y "Şafak renklerinden başlayarak, gün ortası ve ardından geceye kadar giderek."
    y "Boyalar kuruyunca pankartın üstüne ilham verici bir özdeyiş yazacağım."
    y "Pankartı sınıfın önündeki kürsünün arkasındaki duvara asabiliriz."
    mc "A, güzel."
    mc "Pankarta ne yazacaksın?"
    y 2bm "Şey..."
    y "... Sana sürpriz olsun, öylesi daha eğlenceli."
    "Yuri bana gülümsüyor."
    mc "Madem öyle diyorsun..."
    show yuri zorder 1 at thide
    hide yuri
    "Pankart için kullanacağımız kağıdı açtıktan sonra birbirimize mani olmamak için karşı köşelerde dizlerimizin üstünde oturuyoruz."
    "Yuri, boyarken kılavuz görevi görmeleri için pankart kağıdının üstüne farklı renklerde noktalar damlatıyor."
    mc "Bu bana ilkokulu anımsattı..."
    "Sulu boyayla pankart hazırlamak ilkokuldayken resim dersinde yaptığımız şeylere çok benziyor."
    "Sakinleştirici bir şey."
    show yuri 2bt zorder 2 at t11
    y "A..."
    y "Çok çocukçaymış gibi geliyorsa üzgünüm!.."
    mc "Hayır, onu kastetmedim."
    mc "Eğlenceli bir şey sadece."
    y 1bs "... Evet."
    y "Eğlenceli."
    y "Senin de öyle düşünmene sevindim."
    "Yuri boyamayı kesip bir süre kendi kendine düşünüyor."
    y 2bl "Şahsen..."
    y "Eğlenmek için çıkıp çılgınca şeyler yapmama gerek yok."
    y "Hatta, genelde yapmak bile istemiyorum."
    y 2bf "Sadece başka biriyle birlikte zaman geçirmeyi seviyorum..."
    y "Gerekirse okumak gibi basit bir şey olsun, çok konuşmasak bile bir önemi yok."
    y 2ba "Sadece yanımda bir arkadaşımın olması her şeyi biraz daha güzel kılıyor."
    y "Sanırım mutlu olmam için bu kadarı yeterli."
    mc "Demek öyle..."
    "Yuri ile ben epey farklı olsak bile onun kastettiği şeyi anlayabiliyorum."
    "Animeler ve oyunlar hakkında ben de aynı şeyi düşünüyorum; tecrübemi bir başkasıyla paylaşmak tek başına beni mutlu etmeye yetiyor."
    mc "Sanırım ben de aynı şekilde düşünüyorum."
    "Yuri zarifçe gülümsüyor."
    y 1bm "Anlayacağını biliyordum..."
    "Yuri, kullanılmamış bir fırça almak için pankartın üzerine uzanıyor."
    "Ama ben de onunla aynı zamanda hareket ettiğimden kafalarımız çarpışıyor."
    y 3bn "Ay—!"
    mc "Ö-Özür dilerim!"
    "Yuri geriye eğiliyor, ben de şaşkınlıktan çabucak ellerimi kaldırıyorum."
    mc "Bir şeyin var mı?"
    y 2bv "H-Hayır, yok."
    y "Sadece şaşırdım... Hepsi bu."
    y "Özür dilerim, senden fırçayı uzatmanı rica etmeliydim..."
    mc "Senin suçun değil."
    mc "Ah, yüzün..."
    "Yuri’nin yüzünde ve boynunda boya damlaları var."
    y 2bt "Yüzümde bir şey mi var?"
    mc "Evet, yanlışlıkla üzerine boya bulaştırmışım..."
    mc "Özür dilerim, bu tamamen benim hatam!"
    mc "Hemen bir havlu getireceğim."
    show yuri zorder 1 at thide
    hide yuri
    "Aceleyle odadan çıkıp küçük bir havlu buluyorum ve sıcak suyla ıslatıyorum."
    "Odama dönüp onun önünde dizlerime çöküyorum."
    $ persistent.clear[5] = True
    scene y_cg3_base with dissolve_cg
    mc "İşte..."
    "Havluyla Yuri’nin yüzünü ve boynunu siliyorum."
    show y_cg3_exp1 at cgfade
    y "Ah—"
    mc "Bir sorun mu var?"
    y "Sıcakmış... Bunu beklemiyordum."
    mc "Özür dilerim..."
    mc "Soğuk su kullanmak istemedim."
    "İşim bittiğinden elimi geri çekmeye başlıyorum."
    "Ama Yuri aniden bileğimi tutuyor."
    hide y_cg3_exp1
    y "Dur—"
    mc "Ha?"
    show y_cg3_exp1 at cgfade
    y "Azıcık... daha."
    y "Çok güzel geliyor..."
    mc "A..."
    "Elimi Yuri’nin boynunda tutmaya devam ediyorum."
    hide y_cg3_exp1
    "Yuri gözlerimin içine bakıyor."
    "Yüzünde kitaplarını okurken takındığını bildiğim ciddi bir ifade var..."
    "Sanki başka diyarlara dalmış, düşüncelerinde boğulmuş gibi."
    "Yuri, hafif aralık olan dudaklarından yavaşça nefes alıp veriyor."
    "Neler oluyor?.."
    "Yasemin esansının aroması mı bana bu baş döndürücü hissi yaşatan?"
    "Yuri’nin bileğimi kavrayan zarif parmakları koluma bir karıncalanma hissi yayıyor."
    "Bir de, Yuri’nin yüzü birden benimkine daha da yakınlaşmış sanki..."
    y "A..."
    "Yuri yavaşça geri çekiliyor."
    y "Özür dilerim..."
    y "Bugün biraz sersemlik var üzerimde."
    y "Dalıp gitmek istememiştim..."
    mc "S-Sorun değil..."
    scene bedroom with dissolve_cg
    "Bu özel an başladığı gibi bitti."
    "Yuri tekrar fırçasını eline alıyor."
    "Ama hareketleri biraz dengesiz, sanki odaklanamıyor gibi."
    "Sessizliğimi koruyor, az önce yaşanan olayı görmezden gelmek zorunda kalıyorum."
    "Çekinerek kendi fırçamı alıyorum ve Yuri’yi örnek alarak işime devam ediyorum."

    scene bedroom with wipeleft_scene
    mc "Bu yeterli olsa gerek..."
    "Gece göğünü yıldızlara benzeyen beyaz noktalarla donatarak işimi bitiriyorum."
    "Pankarta şöyle baştan sona bakınca oldukça güzel ve doğal görünüyor."
    show yuri 1ba zorder 2 at t11
    y "Sanırım beklediğimden daha iyi bir şey ortaya çıktı."
    y "Sonuçlardan oldukça memnunum."
    mc "Ben de."
    mc "Yazıyı şimdi mi ekleyeceksin?"
    y 1bf "A, şimdi değil..."
    y "Önce kuruması lazım."
    mc "Doğru ama uzun sürmez mi?"
    y 2bh "Hm..."
    y "En iyisi onu burada bırakmak olacak o hâlde. Yarın sen getirirsin."
    y 2bf "Yazıyı etkinlik başlamadan önce sınıfta eklerim."
    y "Olur mu?"
    mc "Elbette."
    y 1ba "Harika."
    y "Öyleyse..."
    y "Yapacak başka bir şey kalmadı."
    mc "Hüff."
    y 1bc "Ahaha."
    y "Bitmesine sevinmiş gibisin."
    y 1ba "Bu işi yaparken en azından biraz eğlenmiştin, yanılıyor muyum?"
    mc "A, yok ondan değil."
    mc "Sadece her şeyi bitirebildiğimize sevindim."
    y 2ba "Anladım."
    y "Ben de sevindim."
    y "Zaman yetmeyebilir diye endişelenmiştim..."
    y "Benim akşam yemeğini hazırlamam lazım."
    mc "A..."
    mc "Hiç zamanın kalmadı mı?"
    "Gizliden gizliye işimiz bitince biraz birlikte vakit geçiririz diye umuyordum..."
    y 2bl "Şey..."
    y "..."
    "Yuri kendi kendine düşünüyor."
    y 3bv "D-Daha fazla beklersem fazla sorumsuzluk etmiş olurum..."
    y "Özür dilerim!"
    y "Ben de daha fazla zaman kalır diye umuyordum..."
    mc "Bu muhtemelen benim suçum."
    mc "Bu kadar yavaş çalıştığım için üzgünüm."
    y 1bt "Hayır, bu senin suçun falan değil."
    y "Ve... asıl önemli olan her şeyi bitirmiş olmamız, değil mi?"
    mc "Evet..."
    y 1bu "O yüzden..."
    y "Hayal kırıklığına uğramış... falan olmamalıyım."
    "Tüm eşyalarını toplayan Yuri’nin morali biraz bozuk görünüyor."
    "Sebebini anlıyorum."
    "Arkadaşlarıyla birlikte sessiz sakin bir ortamda nadiren vakit geçirme fırsatı buluyor olmalı."
    "Ama bu, bunun son kez olacağı anlamına gelmiyor..."

    scene bg house with wipeleft_scene
    "Yuri toplandıktan sonra ona kapıya kadar eşlik ediyorum."
    show yuri 1ba zorder 2 at t11
    y "Bugün beni ağırladığın için çok teşekkür ederim."
    mc "Sorun değil, yardımcı olabildiğime sevindim."
    mc "Yarın getirmem gereken başka bir şey olursa haber et."
    y "Ederim."
    y 1bu "Pekâlâ..."
    "Yuri huzursuz görünüyor."
    y 2bu "Şey... Yarın görüşürüz."
    mc "Dur—"
    show yuri 2bt
    "Bunu biraz düşünmeden söylüyorum."
    mc "Bugün..."
    mc "İstediğimiz kadar zamanımızın olmaması sorun değil."
    mc "Çünkü bunu tekrar edebiliriz."
    mc "Ne zaman istersen buraya gelebilirsin ya da birlikte dışarı—"
    mc "Ah, dışarı çıkmayı sevmediğini unuttum—"
    show yuri 2bs
    "Sözlerimi karıştırırken Yuri sadece utangaç bir şekilde gülümsüyor."
    mc "Her neyse..."
    mc "Ne demeye çalıştığımı biliyorsun..."
    y 1bs "Çok düşüncelisin, [player]."
    "Yuri bana yaklaşıyor ve elimi kısa bir süre sıkıyor."
    show yuri 2bs at face(y=600) with dissolve
    stop music fadeout 2.0
    y "Senin bu yanını seviyorum..."
    mc "Şey..."
    "Buna nasıl yanıt vermem gerekiyor?"
    "Ama yanıt verme şansım bile olmuyor çünkü Yuri ansızın geri çekiliyor."
    show yuri 3bn zorder 2 at t11
    y "S-Sayori—?"
    mc "Ha?!"
    show sayori 1bl zorder 3 at f21
    show yuri zorder 2 at t22
    s "A..."
    s "S-Selam, [player]..."
    mc "Sayori—!"
    mc "Biz az önce—"
    s 1bq "Ehehe~"
    s "Önemli değil, [player]."
    s 1ba "Sadece selam vermek için uğramıştım~"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 3bq "Ş-Şey..."
    y "Seni görmek güzel..."
    y 3bv "Üzgünüm ama zaten eve dönmek üzereydim!"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "Ya, cidden mi?"
    s "Çok kötü oldu..."
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 2bt "Üzgünüm..."
    y "Ama yarın hep birlikte olacağız zaten..."
    y "Sorun olmaz, değil mi?"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 4bq "Tabii ki!"
    "Sayori gülümsüyor."
    show sayori 4ba
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 4bc "T-Tamam, öyleyse..."
    y "Yarın görüşürüz!"
    show yuri at lhide
    hide yuri
    "Utandığı bariz olan Yuri aceleyle gidiyor."
    "Sayori ona el sallıyor."
    return



label ch4_end:
    play music t10 fadeout 2.0
    show sayori 1ba zorder 2 at t11
    mc "Sayori—"
    mc "Bugün gelmek istemediğini sanıyordum!"
    s 2bl "Ahaha, şey..."
    s "Odamda kalmayı denedim..."
    s "Ama hayal gücüm bana oyun oynayıp durdu..."
    s 1by "O yüzden gelip kendi gözlerimle görmeliydim."
    mc "Neyi görmeliydin?"
    mc "Neden bahsediyorsun?"
    s "Şeyi ya..."
    s "[ch4_name] ile ne kadar eğlendiğini."
    s "Ve ona ne kadar yakınlaştığını."
    s 1bt "Bu beni... çok mutlu ediyor..."
    s "Bu kadar iyi arkadaşlar edinmen yani."
    s "Benim için en önemli şey bu."
    "Sayori’nin gözlerinden aşağı yaşlar süzülüyor."
    s 4bv "Benim için en önemli şey bu—!"
    s "Neden böyle hissediyorum, [player]?"
    s "Senin adına mutlu olmam gerekir."
    s 4bw "Ama neden kalbim ikiye ayrılıyormuş gibi hissediyorum?"
    s "Çok canım yanıyor..."
    s "Her şey canımı yakıyor..."
    s "Yok olsam her şey çok daha iyi olurdu!"
    mc "Sayori, deme öyle!"
    s 1bw "Ama bu doğru, [player]!"
    s "Ben burada olmasaydım bana acımak zorunda kalmazdın!"
    s "Bencilliğime katlanmak zorunda kalmazdın!"
    s 1bv "Monika haklıydı..."
    s "Ben gidip..."
    mc "Monika?.."
    mc "Monika ne konuda haklıydı?"
    s "..."
    mc "Sayori..."
    mc "Önceden dediklerim doğru."
    mc "Bunun devam etmesine izin vermeyeceğim."
    mc "Seni önemsemek sandığın gibi bir yük değil benim için."
    mc "Bu beni mutlu eden bir şey."
    mc "Hiçbir şeye değişmeyeceğim türden bir şey."
    mc "O yüzden, bu bir ömür sürse de..."
    mc "Sen acı hissetmeyene dek yanında olacağım."
    s 1bk "A-Ama..."
    "Sayori bakışlarını çeviriyor."
    "Ona güven vermek için elimi omzuna koyuyorum."
    s "Korkuyorum, [player]..."
    s "Çok korkuyorum..."
    mc "Neden korkuyorsun, Sayori?"
    s "Senden, senin benden..."
    s "Hoşlandığından daha çok hoşlanmaktan korkuyorum..."
    mc "Sayori?.."
    s 1bu "Bu doğru, değil mi?"
    s "Güçsüzdüm ve senden çok fazla hoşlanmaya başladım..."
    s "Bunu kendime ben yaptım."
    s "[player]..."
    s 4bw "Senden o kadar çok hoşlanıyorum ki ölmek istiyorum!"
    s "Böyle hissediyorum!"
    s 2bv "Ve... ve..."
    mc "Bu kadarı yeter, Sayori..."
    mc "Seni daha fazla incitmek istemiyorum."
    "Elimi Sayori’nin kolundan indiriyorum ve elini tutuyorum."
    mc "Senin için en iyisini hep bildiğimi söylediğimi hatırlıyor musun?"
    mc "Bana hâlâ inanıyor musun?"
    "Sayori tek kelime etmeden başını sallayarak onaylıyor."
    mc "Kendi hislerinin hepsini anlamasan bile..."
    mc "Şu an en çok ihtiyacın olan şeyi biliyorum."
    mc "Ve sana onu vereceğim."
    show black zorder 4 with dissolve_cg

    menu:
        mc "Sayori..."
        "Seni seviyorum.":

            $ sayori_confess = True
            hide black with dissolve_cg
            call ch4_end_yes
        "Sen her zaman benim en iyi arkadaşım olacaksın.":
            $ sayori_confess = False
            hide black with dissolve_cg
            call ch4_end_no

    return

label ch4_end_yes:
    mc "Seni seviyorum."
    s 1bv "Ha—?"
    mc "Bunlar benim gerçek hislerim."
    mc "O yüzden... senin benden, benim senden hoşlandığımdan daha çok hoşlanman imkânsız."
    mc "Bunu daha erken fark etmeliydim."
    mc "Ama kulüptekilerle zaman geçirmek..."
    mc "Yeni arkadaşlar edinmek..."
    mc "Ve her gün seninle eğlenmek..."
    mc "Senin cidden benim için en değerli kişi olduğunu fark etmemi sağladı."
    mc "Bu yüzden yüklerini sırtlanacağım."
    mc "Yeter ki her gün böyle devam etsin..."
    mc "Sen yanımda ol..."
    mc "Böylelikle ikimizin de mutlu olacağını biliyorum."
    s "[player]..."
    $ persistent.clear[8] = True
    scene s_cg3 with dissolve_cg
    "Aniden Sayori kollarıyla beni sıkıca sarıyor."
    s "[player]..."
    s "Bundan... emin misin?"
    mc "Evet."
    "Sayori’ye sarılıyorum ve onu kendime çekiyorum."
    mc "Beni bir daha bırakmak zorunda kalmayacaksın."
    s "Seni seviyorum, [player]..."
    s "Sonsuza kadar seninle birlikte olmak istiyorum."
    mc "Ben de seninle."
    s "..."
    "Sayori’nin kavrayışının biraz gevşediğini hissediyorum."
    s "Bu da ne?.."
    mc "Sayori?.."
    s "Şu an mutlu olmam gerekir..."
    s "Bunun hep en mutlu anım olacağını düşünmüştüm."
    s "Ama neden?.."
    s "Şimdi bile..."
    s "Yağmur bulutları kaybolmuyor?"
    s "Bir yere gittikleri yok, [player]..."
    mc "Dert etme, Sayori..."
    mc "Her şeyin düzelmesi biraz zaman alabilir."
    mc "Ama ne kadar sürerse sürsün, her adımında senin yanında olacağım."
    mc "Şu an tek önemli olan şey bu."
    s "T-Tamam..."
    s "Sana... güveniyorum..."
    scene bg house
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Birbirimizi yavaşça bırakıyoruz."
    mc "O yüzden..."
    mc "O hâlde, yarınki festival... ilk randevumuz olacak, ha?"
    s 1by "Ehehe..."
    s "Ne diyorsun sen?"
    s "Bu şeyleri düşünmek istemiyorum ben."
    s "Her şeyin olduğu gibi kalmasını istiyorum."
    s "Sevgili olsak... bile."
    s 1bk "Şu an herhangi bir şeyle baş edebilir miyim bilmiyorum..."
    s "Her şey benim için yeni ve korkutucu."
    mc "Anlıyorum."
    mc "Sana uyan bir tempoda ilerleriz."
    s 1bd "Hey, [player]..."
    "Sayori tekrar bana bakıyor, buruk bir gülümsemeyle."
    s 4bd "Çok, çok üzülürsem bile..."
    s "Benim için en iyisi bu... değil mi?"
    mc "Hm?.."
    "Sayori bununla neyi kastediyor cidden anlamıyorum."
    mc "Bunun seni üzdüğünü mü söylüyorsun, Sayori?"
    s 4bk "B-Bilmiyorum..."
    s "Ne hissettiğimi anlamıyorum."
    s "Beni sevdiğini söylediğinde dikenler batıyormuş gibi hissettim..."
    s 4bd "Ama bu yüzden sana güvenmek istiyorum."
    s "Benim için en iyi olanı biliyorsun..."
    mc "... Evet."
    mc "Biliyorum."
    mc "Sana bunun sözünü veriyorum."
    show sayori zorder 1 at thide
    hide sayori
    "Öyle diyorum ama gerçekte bu konu hakkında o kadar kararsızım ki."
    "Onu sevdiğimi biliyorum, onun da beni sevdiğini."
    "Ama Sayori’nin şu anki hislerini anlamakta onun kadar sıkıntı çekiyorum."
    "Onu rahatlatabilsem bile..."
    "Bundan daha fazlasını mı yapmalıyım yoksa daha farklı bir şey mi yapmalıyım diye düşünüp duruyorum."
    "Sayori’nin durumu düzelene kadar bu düşüncelerin aklımı tırmalayacağını biliyorum."
    "Sayori’nin hiçbir şeyin değişmesini istememesinden kastettiği şey bu mu?"
    "Bilmiyorum."
    "Ama elimden gelen her şeyi yapacağımı biliyorum."
    "Sayori hayatımdaki en değerli kişi."
    "Ve onunla mutlu bir gelecek geçirmek için ne gerekiyorsa yapacağım."
    return


label ch4_end_no:
    mc "Sen her zaman en iyi arkadaşım olacaksın."
    mc "Senin en çok ihtiyacın olan şey her şeyin eskisi gibi devam etmesi."
    mc "Monika bana gerçeği söyledi..."
    mc "Senin kulübe katıldıktan sonra ne kadar mutlu göründüğünü söyledi."
    mc "Şu an çok karmaşık duygularla boğuştuğunu biliyorum."
    mc "Ama..."
    mc "Ama lütfen senin için ne iyi olduğunu... ve seni en çok mutlu edecek şeyin ne olduğunu bildiğim konusunda bana güven"
    mc "Her şeyin eski hâline gelmesine yardım edeceğime söz veriyorum."
    s 1bt "A..."
    s "Anlı... yorum..."
    "Sayori yüzündeki inanılmaz derecedeki kederli ifadeye rağmen kendini gülümsemeye zorluyor."
    s "Ahaha..."
    s "Göğsünden bıçaklanmak... böyle bir his midir acaba?"
    s "Bu konuda bir şiir yazmalıyım..."
    mc "Sayori—"
    s "Sorun değil."
    s "Bu benim cezam... Hatırladın mı?"
    s "Bu kadar bencil olduğum için..."
    s "O yüzden lütfen..."
    s "Lütfen bu aptalca hisleri kafana takma."
    s "Haklı olduğunu biliyorum."
    s "Bu yolun ardında hiç mutluluk olmadığını hep biliyordum."
    s "Bu yüzden buraya geldim..."
    s "Duymam gereken cevabı alabilmek için."
    s "Bir şey daha..."
    s "Her şeyin eski hâline dönmesini istediğim konusunda da haklısın."
    s "Bunu şimdi fark ediyorum."
    s "Beni gerçekten herkesten daha iyi tanıyorsun, [player]."
    s 4bv "Sana her konuda güveneceğim..."
    s "Her konuda..."
    s "O yüzden..."
    show sayori zorder 1 at thide
    hide sayori
    "Sayori’nin gülümsemesi sonunda bozuluyor."
    "Birden arkasına dönüp dizleri üstüne çöküyor."
    s "{i}AAAAAaaaaAAAAAAAAHH!!!!{/i}"
    "İki eliyle de kafasını tutup olabildiğince şiddetli bir şekilde çığlık atıyor."
    "O kadar şaşkınım ki nasıl tepki vereceğimi bilmiyorum."
    show sayori 4bt zorder 2 at t11
    s "..."
    show sayori at lhide
    hide sayori
    "Sayori, arkasını dönüp son bir kez zayıf bir gülümsemeyle bana bakıyor ve ardından kaçıp gidiyor."
    mc "Sayori!"
    "..."
    "Çaresiz bir şekilde evimin önünde duruyorum."
    "Neden bu konuda bu kadar kötü hissediyorum?"
    "Daha fazla yapabileceğim bir şey yok."
    "Sayori için elimden en fazla yaşadıkları sırasında ona destek olmak ve onu doğru yola yönlendirmek gelir."
    "Ama Sayori’nin şu anki hislerini anlamakta onun kadar sıkıntı çekiyorum."
    "Onu rahatlatabilsem bile..."
    "Bundan daha fazlasını mı yapmalıyım yoksa daha farklı bir şey mi yapmalıyım diye düşünüp duruyorum."
    "Sayori’nin durumu düzelene kadar bu düşüncelerin aklımı tırmalayacağını biliyorum."
    "Elimden geleni yapacağım."
    "Sayori her zaman benim en iyi arkadaşım olacak."
    "Ve her gün onu gülümsetebilmek için ne gerekirse yapacağım."

    return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
